#the server port.
server:
  port: 8080

#mybaits-plus
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tu-cao-ba?useUnicode=true&characterEncoding=utf8
  batch:
    jdbc:
      table-prefix: tc_