# 项目相关配置
death:
  # 名称
  name: Tu-Cao-Ba
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/death/uploadPath，Linux配置 /home/death/uploadPath）
  profile: D:/death/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

#envirment
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
  data:
    # redis 配置
    redis:
      # 地址
      host: 127.0.0.1
      # 端口，默认为6379
      port: 6379
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  main:
    allow-bean-definition-overriding: true

#defalut context-path
server:
  servlet:
    context-path: /tcb

#knife4j
knife4j:
  enable: true
  openapi:
    title: 吐槽吧，接口文档
    description: 在线即实聊天
    email: 21171326@qq.com
    concat: Iga
    url: https://aalo.cn
    version: v1.0.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: Iga
        api-rule: package
        api-rule-resources:
          - cn.envisions.tucaoba.controller


# token
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30


#logger

# 开启Shiro注解
logging:
  level:
    org.springframework.web: DEBUG
